language: c

sudo: false

addons:
  postgresql: "9.4"

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install luasocket
  - luarocks install luasec
  - luarocks install moonscript
  - luarocks install lua-cjson
  - luarocks install cqueues
  - luarocks make

script:
  - busted

